In [ ]:
import pandas as pd


In [2]:
df_1 = pd.read_excel('diem_f1_md.xlsx')

In [3]:
df_2 = pd.read_excel('diem_f2_md.xlsx')

In [4]:
print(df_1.shape)
print(df_1.info())
print(df_1.columns)

(500000, 33)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 33 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   NAMHOC      500000 non-null  int64  
 1   TENHK       500000 non-null  int64  
 2   NHHK        500000 non-null  int64  
 3   F_MAMH      500000 non-null  object 
 4   F_TENMHVN   500000 non-null  object 
 5   F_DVHT      500000 non-null  float64
 6   F_PHTRAMKT  500000 non-null  int64  
 7   F_PHTRAMTH  500000 non-null  int64  
 8   F_MANH      500000 non-null  object 
 9   F_TO        405069 non-null  object 
 10  STT         436587 non-null  float64
 11  F_MAKH      500000 non-null  object 
 12  F_TENLOP    500000 non-null  object 
 13  F_KHOI      500000 non-null  object 
 14  F_MANG      500000 non-null  object 
 15  F_TENNGVN   500000 non-null  object 
 16  MASV1       500000 non-null  int64  
 17  KT          414857 non-null  float64
 18  TILEKT      414858 non-null  fl

In [5]:
print(df_2.shape)
print(df_2.info())
print(df_2.columns)

(500000, 33)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 33 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   NAMHOC      500000 non-null  int64  
 1   TENHK       500000 non-null  int64  
 2   NHHK        500000 non-null  int64  
 3   F_MAMH      500000 non-null  object 
 4   F_TENMHVN   500000 non-null  object 
 5   F_DVHT      500000 non-null  float64
 6   F_PHTRAMKT  500000 non-null  int64  
 7   F_PHTRAMTH  500000 non-null  int64  
 8   F_MANH      500000 non-null  object 
 9   F_TO        500000 non-null  object 
 10  STT         0 non-null       float64
 11  F_MAKH      499994 non-null  object 
 12  F_TENLOP    500000 non-null  object 
 13  F_KHOI      500000 non-null  object 
 14  F_MANG      500000 non-null  object 
 15  F_TENNGVN   499994 non-null  object 
 16  MASV1       500000 non-null  int64  
 17  KT          163076 non-null  float64
 18  TILEKT      163076 non-null  fl

In [6]:
print(df_1.NHHK.unique())
print(df_2.NHHK.unique())

[151 152 153 161 162]
[162 163 171 172  71  72]


In [7]:
df_1.columns.intersection(df_2.columns).shape

(33,)

In [8]:
df_final = pd.concat([df_1, df_2])

In [9]:
df_final.NHHK.unique()

array([151, 152, 153, 161, 162, 163, 171, 172,  71,  72])

In [10]:
df_final.reset_index(drop=True, inplace=True)

In [11]:
print(df_final.shape)
print(df_final.info())
print(df_final.columns)

(1000000, 33)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 33 columns):
 #   Column      Non-Null Count    Dtype  
---  ------      --------------    -----  
 0   NAMHOC      1000000 non-null  int64  
 1   TENHK       1000000 non-null  int64  
 2   NHHK        1000000 non-null  int64  
 3   F_MAMH      1000000 non-null  object 
 4   F_TENMHVN   1000000 non-null  object 
 5   F_DVHT      1000000 non-null  float64
 6   F_PHTRAMKT  1000000 non-null  int64  
 7   F_PHTRAMTH  1000000 non-null  int64  
 8   F_MANH      1000000 non-null  object 
 9   F_TO        905069 non-null   object 
 10  STT         436587 non-null   float64
 11  F_MAKH      999994 non-null   object 
 12  F_TENLOP    1000000 non-null  object 
 13  F_KHOI      1000000 non-null  object 
 14  F_MANG      1000000 non-null  object 
 15  F_TENNGVN   999994 non-null   object 
 16  MASV1       1000000 non-null  int64  
 17  KT          577933 non-null   float64
 18  TILEKT   

In [12]:
df_final.drop_duplicates(keep="first", inplace=True)

In [13]:
df_final.TKET.unique()

array([4, 6, 8.5, 9.5, 7.5, 5.5, 8, 13, 6.5, 7, 4.5, 9, 3.5, 5, 1.5, 2, 3,
       1, 15, 0, 2.5, 0.5, 10, 11, 2.7, 2.6, 2.25, 2.4, 1.6, 1.4, 2.9,
       1.8, 2.2, 1.7, 1.9, 2.83, 0.22, 2.29, 0.87, 0.32, 0.01, 0.34, 2.1,
       2.8, 2.51, 0.46, 2.57, 2.79, 1.31, 1.95, 1.99, 1.65, 2.81, 2.48,
       0.6, 0.8, 2.3, 0.4, 1.3, 2.55, 0.9, 1.2, 8.79, 9.14, 9.07, 8.64,
       8.57, 8.42, 8.92, 9.21, 5.25, 4.38, 7.66, 6.6, 8.2, 3.52, 6.28,
       8.47, 'CT', 'VT', 'RT', 'IH', 12, 'HT', 'KD', 'DT', 21, 8.67, 8.7,
       8.75, 9.33, 7.92, 8.83, 9.83, 9.1, 9.42, 9.25, 8.9, 9.67, 8.17,
       9.08, 9.3, 8.6, 8.4, 9.17, 9.45, 9.37, 9.73, 7.83, 9.52, 9.13, 9.4,
       9.06, 8.37, 9.23, 9.57, 9.32, 9.18, 9.47, 8.87, 8.93, 9.51, 8.36,
       7.86, 7.36, 7.7, 7.8, 7.64, 8.07, 8.08, 7.43, 8.25, 8.29, 6.67,
       7.79, 7.57, 8.1, 7.33, 6.86, 7.6, 9.05, 7.93, 7.14, 8.14, 9.79,
       8.43, 8.71, 9.75, 8.05, 6.71, 7.17, 8.21, 8.28, 7.85, 8.8, 7.9,
       9.36, 6.08, 6.66, 6.16, 7.87, 9.31, 7.63, 7.77, 7.97

In [14]:
special_score = ['CT', 'MT', 'VT', 'RT', 'IH', 'HT', 'KD', 'DT', 'VP', 11, 12, 13, 14, 15, 16, 17, 20, 21, 22]

In [15]:
df_final = df_final.query('TKET not in @special_score')

In [16]:
df_final.TKET = df_final.TKET.astype(float)

In [17]:
print(len(df_final["F_TENMHVN"].unique()))
print(len(df_final["F_MAMH"].unique()))
print("Giải tích 1 has 3 subject codes: "+ str(df_final[df_final['F_TENMHVN'] == "Giải tích 1"]["F_MAMH"].unique()))
print("Những ngLý cơbản cn M-Lê has the subject code: "+ str(df_final[df_final['F_TENMHVN'] == "Những ngLý cơbản cn M-Lê"]["F_MAMH"].unique()))
print("Những NgLý cơbản CN M-Lê has the subject code: "+ str(df_final[df_final['F_TENMHVN'] == "Những NgLý cơbản CN M-Lê"]["F_MAMH"].unique()))

2508
3256
Giải tích 1 has 3 subject codes: [6001 6401 'MT1003' 6801]
Những ngLý cơbản cn M-Lê has the subject code: [1001]
Những NgLý cơbản CN M-Lê has the subject code: ['SP1003']


In [18]:
df_final.F_MAMH = df_final.F_MAMH.astype(str)

In [19]:
print(df_final[df_final.F_MAMH.str.len() > 6].F_MAMH.unique())
print(df_final[df_final.F_MAMH.str.len() < 6].F_MAMH.unique())

[]
['1001' '1004' '1025' '3001' '3002' '3003' '3004' '3106' '3107' '3109'
 '3701' '3703' '3705' '3707' '3709' '3720' '3722' '3724' '5005' '5006'
 '5011' '6001' '6002' '6004' '6018' '6019' '6023' '6043' '6045' '6046'
 '6401' '6402' '6404' '6405' '6407' '6601' '6602' '6711' '6713' '6714'
 '7001' '7002' '7005' '7017' '7024' '7025' '7029' '7031' '7034' '7035'
 '7036' '7037' '7039' '7041' '7045' '7120' '7401' '7402' '7403' '7404'
 '7601' '7703' '7704' '7705' '7706' '7710' '8001' '8701' '3108' '3110'
 '3401' '3702' '3704' '3706' '3708' '3721' '3723' '3728' '3730' '6007'
 '6712' '6717' '6718' '6719' '7020' '7021' '7023' '7026' '7030' '7032'
 '7033' '7038' '7040' '7043' '7044' '7109' '7119' '7707' '7708' '7709'
 '7302' '3727' '3729' '7003' '7303' '6406' '1011' '3017' '3103' '3104'
 '7016' '6020' '1012' '7027' '7028' '3016' '6038' '7022' '7300' '7110'
 '3024' '1022' '6041' '7301' '7014' '1021' '6039' '3045' '6048' '6805'
 '7803' '6029' '3807' '4009' '4010' '4011' '3022' '1059' '3041' '5010'
 '7

In [20]:
df_final.loc[df_final['F_MAMH'].str.len() == 4, 'F_MAMH'] = "00" + df_final.F_MAMH

In [21]:
df_final.columns.duplicated().any()

False

In [22]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 914924 entries, 0 to 999999
Data columns (total 33 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   NAMHOC      914924 non-null  int64  
 1   TENHK       914924 non-null  int64  
 2   NHHK        914924 non-null  int64  
 3   F_MAMH      914924 non-null  object 
 4   F_TENMHVN   914924 non-null  object 
 5   F_DVHT      914924 non-null  float64
 6   F_PHTRAMKT  914924 non-null  int64  
 7   F_PHTRAMTH  914924 non-null  int64  
 8   F_MANH      914924 non-null  object 
 9   F_TO        829649 non-null  object 
 10  STT         384131 non-null  float64
 11  F_MAKH      914918 non-null  object 
 12  F_TENLOP    914924 non-null  object 
 13  F_KHOI      914924 non-null  object 
 14  F_MANG      914924 non-null  object 
 15  F_TENNGVN   914918 non-null  object 
 16  MASV1       914924 non-null  int64  
 17  KT          508905 non-null  float64
 18  TILEKT      508905 non-null  float64
 19  BT

In [32]:
df_final.NHHK.unique()

array([151, 152, 153, 161, 162, 163, 171, 172])

In [31]:
df_final.NAMHOC.unique()

array([2015, 2016, 2017])

In [25]:
other_years_1 = [71, 72]

In [26]:
df_final = df_final[~df_final.NHHK.isin(other_years_1)]

In [27]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 677117 entries, 0 to 760731
Data columns (total 33 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   NAMHOC      677117 non-null  int64  
 1   TENHK       677117 non-null  int64  
 2   NHHK        677117 non-null  int64  
 3   F_MAMH      677117 non-null  object 
 4   F_TENMHVN   677117 non-null  object 
 5   F_DVHT      677117 non-null  float64
 6   F_PHTRAMKT  677117 non-null  int64  
 7   F_PHTRAMTH  677117 non-null  int64  
 8   F_MANH      677117 non-null  object 
 9   F_TO        591842 non-null  object 
 10  STT         384131 non-null  float64
 11  F_MAKH      677115 non-null  object 
 12  F_TENLOP    677117 non-null  object 
 13  F_KHOI      677117 non-null  object 
 14  F_MANG      677117 non-null  object 
 15  F_TENNGVN   677115 non-null  object 
 16  MASV1       677117 non-null  int64  
 17  KT          508905 non-null  float64
 18  TILEKT      508905 non-null  float64
 19  BT

In [28]:
df_final.drop(["F_DIEM10", "GHICHU", "T"], axis = 1, inplace = True)

In [29]:
df_final.reset_index(drop=True, inplace=True)

In [30]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677117 entries, 0 to 677116
Data columns (total 30 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   NAMHOC      677117 non-null  int64  
 1   TENHK       677117 non-null  int64  
 2   NHHK        677117 non-null  int64  
 3   F_MAMH      677117 non-null  object 
 4   F_TENMHVN   677117 non-null  object 
 5   F_DVHT      677117 non-null  float64
 6   F_PHTRAMKT  677117 non-null  int64  
 7   F_PHTRAMTH  677117 non-null  int64  
 8   F_MANH      677117 non-null  object 
 9   F_TO        591842 non-null  object 
 10  STT         384131 non-null  float64
 11  F_MAKH      677115 non-null  object 
 12  F_TENLOP    677117 non-null  object 
 13  F_KHOI      677117 non-null  object 
 14  F_MANG      677117 non-null  object 
 15  F_TENNGVN   677115 non-null  object 
 16  MASV1       677117 non-null  int64  
 17  KT          508905 non-null  float64
 18  TILEKT      508905 non-null  float64
 19  BT

In [33]:
df_final.to_csv("diem_clean.csv", index = False)

In [34]:
df_final.F_MAMH.unique()

array(['001001', '001004', '001025', ..., '407408', 'EE3113', 'GE3077'],
      dtype=object)

In [ ]:
df_final.F_MAMH = df_final.F_MAMH.astype(str)

# New Clean

In [1]:
import pandas as pd
df_clean = pd.read_csv("diem_clean.csv", dtype = {"F_MAMH": str})

In [4]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677117 entries, 0 to 677116
Data columns (total 30 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   NAMHOC      677117 non-null  int64  
 1   TENHK       677117 non-null  int64  
 2   NHHK        677117 non-null  int64  
 3   F_MAMH      677117 non-null  object 
 4   F_TENMHVN   677117 non-null  object 
 5   F_DVHT      677117 non-null  float64
 6   F_PHTRAMKT  677117 non-null  int64  
 7   F_PHTRAMTH  677117 non-null  int64  
 8   F_MANH      677117 non-null  object 
 9   F_TO        591842 non-null  object 
 10  STT         384131 non-null  float64
 11  F_MAKH      677115 non-null  object 
 12  F_TENLOP    677117 non-null  object 
 13  F_KHOI      677117 non-null  object 
 14  F_MANG      677117 non-null  object 
 15  F_TENNGVN   677115 non-null  object 
 16  MASV1       677117 non-null  int64  
 17  KT          677117 non-null  float64
 18  TILEKT      677117 non-null  float64
 19  BT

In [12]:
import numpy

In [3]:
# File NA with 0
df_clean["KT"] = df_clean["KT"].fillna(-1)
df_clean["TILEKT"] = df_clean["TILEKT"].fillna(0)
df_clean["BT"] = df_clean["BT"].fillna(-1)
df_clean["TILEBT"] = df_clean["TILEBT"].fillna(0)
df_clean["BTLDA"] = df_clean["BTLDA"].fillna(-1)
df_clean["TILEBTLDA"] = df_clean["TILEBTLDA"].fillna(0)
df_clean["TN"] = df_clean["TN"].fillna(-1)
df_clean["TILETN"] = df_clean["TILETN"].fillna(0)
df_clean["THI"] = df_clean["THI"].fillna(-1)
df_clean["TILETHI"] = df_clean["TILETHI"].fillna(0)


In [5]:
df_clean.to_csv("diem_clean_with_minus1.csv", index = False)

# Clean diem -> -1 when tile is 0

In [7]:
import pandas 
df_clean_2 = pandas.read_csv("diem_clean_with_0.csv", dtype = {"F_MAMH": str})

In [19]:
df_clean_2.F_TENMHVN.value_counts()

Giải tích 1                 13302
Giáo dục thể chất 1         12509
Giáo dục thể chất 2         12164
Thí nghiệm vật lý           11414
Đại số tuyến tính           11412
                            ...  
ĐAMH đánh gía tácđộng mt        1
Thực tập kỹ thuật y sinh        1
Thực tập 1                      1
Các pp xđ ct hợp chất hc        1
ĐAMH tk vịtrí& m/bg htcn        1
Name: F_TENMHVN, Length: 2123, dtype: int64